language: objective-c
env: LC_ALL="en_US.UTF-8"

before_install:
   - sudo easy_install cpp-coveralls
script: xcodebuild -project KFToolbar.xcodeproj -scheme KFToolbar -sdk macosx10.9 test
after_success:
  - ./coveralls.rb --extension m --exclude-folder KFToolbar/Sources/Tests --exclude-folder KFToolbarTests
